### PR TITLE
Replaced XMLHttpRequest with Fetch API

### PR DESCRIPTION
**Pull request by lwcorp**
Fetch API is simpler and yet provides flexibility

I've also added the ability to use alternative encoding (instead of the default UTF-8).

### CODE REVIEW

**Comment by codeit-ninja** [comment]
I dont see the pull request anymore, did you delete it?

**Comment by lwcorp** [comment]
No, and I still see it.
This part is clickable for me leading to [this link](https://github.com/codeit-ninja/SRT-Support-for-HTML5-videos/pull/1/commits/ae21f5f395ff580c51c49272f75e668d98b5ff0a):
image

**Comment by codeit-ninja** [comment]
I am working on a version 2 for a little while already, the usage of the `TextDecoder` is a good addition, I will implement that in v2 aswell. I need to test your PR first before merging.

**Comment by lwcorp** [comment]
Sure, please test, but it works great for me.

In fact, this commit made it easier for me to merge your project with a "text encoding detection" project, then feed the detection of the latter project (if it's not Unicode) into `TextDecoder`.
I then merged it further with my own code to allow choosing files and subtitles/captions via `<input type="file">`, meaning **instead** of your `canplay` event. The only downside is that it means I won't be able to automatically use future upgrades of yours without manually tweaking them too.
You can read more about it in https://github.com/lwcorp/watchparty#history

**Comment by codeit-ninja** [comment]
No need to merge this anymore, I created a new version, which has the features of the PR request included.

**Pull request closed without merging**
